### PR TITLE
Added ability to have rule be on page AND post

### PR DESCRIPTION
**Pull request by ckeboss**
This could be expanded with a multiple selection box to be able to add
as many combinations as you want. But that would need space, and the UI
really should be improved so it can be expanded.

### CODE REVIEW

**Comment by chrisguitarguy** [comment]
I'm not sure about this one.  Obviously it reduces the "shit work" that is entering the same thing on two separate lines.  

What about folks who want the same links on multiple post types that aren't built ins (custom post types)?  Seems like I should just have a sit down and figure out a better UI to make multiple post types work.

Thoughts?

**Comment by ckeboss** [comment]
Yes. This works, as you can see, by just making a csv as the value. It could be expanded by using a multiple select box, on submit, parse post data, make a csv, and save that value. Nothing would have to change in front.php. I can add that, but then the UI starts getting really awkward. Any thoughts on how to change the UI from this row system to something more flexible? I am thinking a row that expands down to edit. This way, inputs can be organized in a more flexible way, and not in a table.

**Comment by chrisguitarguy** [comment]
Not sure yet about the UI.  Going to think about it for a bit, I'll leave this open for now.

Thanks!

**Comment by chrisguitarguy** [comment]
What about a complete change around: switch the UI to a post editing screen.  Eg. store keywords in a custom post type.  Would a lot quite a bit more expansion for what could be done with the keywords.

**Comment by ckeboss** [comment]
But wouldn't that make it that I would have to add my keywords to every page I want? Eg I have a blog, install this plugin to add linking, and now I have to edit every post/page to add linking?

**Comment by chrisguitarguy** [comment]
No, it would.  Just use a custom post type as a container for the keyword data.  And use the post type UI to edit keywords.

**Comment by ckeboss** [comment]
Still not sure what you mean. Where would the user add keywords/urls/everything? I haven't made a wordpress plugin in a little while, so excuse me if I am not updated with the lingo.

**Comment by chrisguitarguy** [comment]
I've got a plan for this now.  Major UI changes that should make it much easier to add multiple post types per keyword set.

**Comment by ckeboss** [comment]
Care to elaborate on the plan?

**Comment by chrisguitarguy** [comment]
Sure! Going to do something similar to this plugin: http://wordpress.org/extend/plugins/shortcode-disabler/screenshots/

Editing/adding area up top, list table of the keywords and such down below.  Also probably going to split other options on to a separate page -- have two admin pages.

The only thing I'm still trying to figure out is whether to keep using the `options` table to store the info about keywords/links or whether to use a a custom post type as a container.  Leaning towards custom post type.

**Comment by ckeboss** [comment]
Sounds like a plan. Let me know if you need anything from me.

-James Barcellano
Php/MySQL/CakePHP Web Developer
http://jamesb.biz/
951-25-GEEK-1
951-25-(4335)-1
james@jamesb.biz

**Comment by chrisguitarguy** [comment]
Check out the newest version.  New admin area!

**Pull request closed without merging**
